import {
  COMPACT_NUMBER_DISPLAY,
  CURRENCY_CODES,
  DATA_FORMAT,
  DATE_OPTIONS,
  PRECISION_VALUES,
  SIGN_DISPLAY,
} from '../types';

export const DEFAULT_NUM_TYPE = DATA_FORMAT[0];
export const DEFAULT_PRECISION = PRECISION_VALUES[2];
export const DEFAULT_COMPACT_DISPLAY = COMPACT_NUMBER_DISPLAY[0];
export const DEFAULT_SIGN_DISPLAY = SIGN_DISPLAY[0];
export const DEFAULT_CURRENCY_CODE = CURRENCY_CODES[2];
export const DEFAULT_MAX_FRACTION_DIGITS = PRECISION_VALUES[2];

export const DEFAULT_NUMBER_OPTIONS = {
  type: DEFAULT_NUM_TYPE,
  precision: DEFAULT_PRECISION,
  compactDisplay: DEFAULT_COMPACT_DISPLAY,
  signDisplay: DEFAULT_SIGN_DISPLAY,
  currencyCode: DEFAULT_CURRENCY_CODE,
};

export const DEFAULT_YEAR_FORMAT = DATE_OPTIONS.year[1];
export const DEFAULT_MONTH_FORMAT = DATE_OPTIONS.month[3];
export const DEFAULT_DAY_FORMAT = DATE_OPTIONS.day[1];

export const DEFAULT_DATE_OPTIONS = {
  year: DEFAULT_YEAR_FORMAT,
  month: DEFAULT_MONTH_FORMAT,
  day: DEFAULT_DAY_FORMAT,
};
